name: Build binaries and upload artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    name: Build binaries for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build binaries for Windows
        run: cargo build --release
      - name: Upload artifacts for Windows
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: target/release/tgh.exe
  build-linux-x86_64:
    name: Build binaries for Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build binaries for Linux x86_64
        run: cargo build --release
      - name: Upload artifacts for Linux x86_64
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: target/release/tgh
         